run_name: ddpm
seed: 45
data_dir: ./data
output_dir: ./experiments
image_size: 128
batch_size: 16 #BATCH_SIZE
accumulation_step: 32
num_workers: 4 #NUM_WORKERS
num_classes: 256 #NUM_CLASSES
num_epochs: 10 #NUM_EPOCHS
learning_rate: 0.0001 #LR
weight_decay: 0.0001 #WD
num_train_timesteps: 40000 #TRAINING_TIMESTEPS
num_inference_steps: 25 #INFERENCE_TIMESTEPS
beta_start: 0.00001 #BETA START
beta_end: 0.01 #BETA END
beta_schedule: cosine #BETA SCHEDULE

variance_type: fixed_small
predictor_type: epsilon
unet_in_size: 128
unet_in_ch: 3
unet_ch: 128
unet_num_res_blocks: 4
unet_ch_mult: [1, 2, 2, 4]
unet_attn: [2, 3]
unet_dropout: 0.01

use_ddim: true
use_cfg: true
latent_ddpm: false
cfg_guidance_scale: 7.5
inference_batch_size: 50


ckpt: experiments/exp-14-ddpm/checkpoints/checkpoint_epoch_9.pth
wandb_key: 68abc6da5d0bfb1c67a41a153e2b2124341b0289
